### ISSUE TITLE
There are no commands defined in the "cron" namespace.

### ISSUE THREAD

**Issue by juniorrosul** [liebig/cron#61]
I was getting the following error when i exec ```php artisan cron:keygen```:
```
[InvalidArgumentException]
There are no commands defined in the "cron" namespace.
```
and here is the log file:
```md
[2015-03-17 09:19:44] user.ERROR: exception 'InvalidArgumentException' with message 'There are no commands defined in the "cron" namespace.' in C:\project\vendor\symfony\console\Symfony\Component\Console\Application.php:516
Stack trace:
#0 C:\project\vendor\symfony\console\Symfony\Component\Console\Application.php(550): Symfony\Component\Console\Application->findNamespace('cron')
#1 C:\project\vendor\symfony\console\Symfony\Component\Console\Application.php(190): Symfony\Component\Console\Application->find('cron:keygen')
#2 C:\project\vendor\symfony\console\Symfony\Component\Console\Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\project\artisan(59): Symfony\Component\Console\Application->run()
#4 {main} [] []
```

app.php:
```php
...
		// CronJobs
		'Liebig\Cron\CronServiceProvider',
...
```

Why i'm getting this error??

**Comment by liebig** [comment]
Hi @juniorrosul,
I am sorry for this issue and I will try to help you. But first please tell me which version of Laravel you use. Does `Cron` works if you execute it via route? You usually get this Exception if the service provider was not added to the `providers` array. So please check your `config/app.php` file:
```php
<?php

...

'providers' => array(
            
                'Liebig\Cron\CronServiceProvider',

		'Illuminate\Foundation\Providers\ArtisanServiceProvider',
...

```

**Comment by liebig** [comment]
Closed due to inactivity
